function renderNotes(){
 const notes=state.data.notes||[];
 return `<div class="card"><div class="card-head"><div><h3>My Notes</h3><p>Ideas, meeting notes, and things worth remembering.</p></div><button class="btn primary" data-new-note>+ New Note</button></div><div class="card-body"><input id="noteSearch" class="field" type="search" placeholder="Search titles and bullet points…" aria-label="Search notes"><div id="notesList" class="notes-list">${notes.map(n=>`<button class="note-tile" data-edit-note="${esc(n.noteId)}" data-search="${esc(((n.title||'')+' '+(n.note||'')).toLowerCase())}"><div class="note-title">${esc(n.title||'Untitled note')}</div><div class="meta">Created ${esc(fmtDate(n.date))}${n.updated?' · Edited '+esc(fmtDate(n.updated.slice(0,10))):''}</div><div class="note-preview">${esc((n.note||'').split('\n').filter(Boolean).slice(0,3).map(t=>'• '+t.replace(/^[•\-]\s*/, '')).join('\n'))}</div></button>`).join('')||empty('No notes yet. Tap New Note to begin.')}</div></div></div>`;
}
function filterNotes(){const q=($('#noteSearch')?.value||'').toLowerCase().trim();$$('[data-edit-note]').forEach(n=>n.style.display=n.dataset.search.includes(q)?'':'none');}
function openNoteForm(n={}){
 const editing=!!n.noteId;
 const bullets=(n.note||'').split('\n').map(t=>t.replace(/^[•\-]\s*/, '')).join('\n');
 openSheet(editing?'Edit Note':'New Note',`<form id="noteForm"><div class="form-grid"><div class="form-group full"><label>Title</label><input class="field" name="title" required maxlength="200" placeholder="Meeting notes, idea, topic…" value="${esc(n.title||'')}"></div><div class="form-group full"><label>Bullet points <span class="muted">(one per line)</span></label><textarea name="note" rows="12" required placeholder="First point&#10;Second point&#10;Third point">${esc(bullets)}</textarea></div></div><div class="meta" style="margin-top:12px">${editing?'Created '+esc(fmtDate(n.date)):'Created date will be recorded automatically'}</div><div class="sheet-actions">${editing?'<button type="button" class="btn" id="deleteNoteBtn" style="margin-right:auto;color:#bb3344">Delete</button>':''}<button type="button" class="btn" data-close-sheet>Cancel</button><button class="btn primary" type="submit">Save Note</button></div></form>`);
 const form=$('#noteForm');
 form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form);const title=String(f.get('title')||'').trim();const note=String(f.get('note')||'').split('\n').map(t=>t.trim().replace(/^[•\-]\s*/, '')).filter(Boolean).join('\n');if(!title||!note)return;const btn=form.querySelector('[type=submit]');btn.disabled=true;try{await busy(bridge.call('saveNote',{noteId:n.noteId||'',title,note,date:n.date||todayIso(),tags:n.tags||'',projectId:n.projectId||'',pinned:n.pinned||'No'}),'Note saved');closeSheet()}catch(err){btn.disabled=false;}};
 $('#deleteNoteBtn')?.addEventListener('click',async()=>{if(!confirm('Delete this note permanently?'))return;try{await busy(bridge.call('deleteNote',n.noteId),'Note deleted');closeSheet()}catch(e){}});
}
