function renderCalendar(){
  const mode=state.calendarMode, title=calendarTitle();
  return `<div class="card"><div class="card-head calendar-toolbar"><div><h3>${esc(title)}</h3><p>Actions + recurring routines</p></div><div class="seg"><button data-cal-mode="month" class="${mode==='month'?'active':''}">Month</button><button data-cal-mode="week" class="${mode==='week'?'active':''}">Week</button><button data-cal-mode="day" class="${mode==='day'?'active':''}">Day</button></div><div class="cal-nav"><button class="btn" data-cal-nav="-1">‹</button><button class="btn" data-cal-today>Today</button><button class="btn" data-cal-nav="1">›</button></div></div><div class="card-body">${mode==='month'?renderMonth():mode==='week'?renderWeek():renderDay()}</div></div>`;
}
function calendarTitle(){const d=state.cursor;if(state.calendarMode==='month')return d.toLocaleDateString(undefined,{month:'long',year:'numeric'});if(state.calendarMode==='day')return d.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});const s=startWeek(d),e=addDays(s,6);return `${fmtDate(s,{month:'short',day:'numeric'})} – ${fmtDate(e,{month:'short',day:'numeric',year:'numeric'})}`;}
function renderMonth(){const d=state.cursor,first=new Date(d.getFullYear(),d.getMonth(),1,12),start=startWeek(first),cells=[];for(let i=0;i<42;i++){const x=addDays(start,i),acts=actionsForDate(x),r=routinesForDate(x),other=x.getMonth()!==d.getMonth(),today=iso(x)===todayIso();cells.push(`<div class="cal-cell calendar-month ${other?'other-month':''} ${(acts.length||r.length)?'has-items':''} ${today?'today-cell':''}"><div class="cal-day ${today?'today':''}"><span>${x.getDate()}</span> <small>${x.toLocaleDateString(undefined,{weekday:'short'})}</small></div>${acts.slice(0,2).map(a=>`<div class="cal-event">${esc(a.task)}</div>`).join('')}${r.length?`<div class="cal-routine">${r.length} routine${r.length===1?'':'s'} · ${r.filter(y=>y.done).length} done</div>`:''}</div>`)}return `<div class="cal-grid">${cells.join('')}</div>`;}
function renderWeek(){const s=startWeek(state.cursor);return `<div class="week-grid">${Array.from({length:7},(_,i)=>{const d=addDays(s,i),a=actionsForDate(d),r=routinesForDate(d);return `<div class="week-day"><h4>${d.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</h4>${a.map(x=>`<div class="cal-event">${esc(x.task)}</div>`).join('')||'<div class="muted">No actions</div>'}${r.length?`<div class="cal-routine">${r.length} routines · ${r.filter(x=>x.done).length} done</div>`:''}</div>`}).join('')}</div>`;}
function renderDay(){const d=state.cursor,a=actionsForDate(d),r=routinesForDate(d);return `<div class="day-list">${a.length?`<h3>Actions</h3>${a.map(x=>`<div class="agenda-item"><strong>${esc(x.task)}</strong><div class="meta"><span class="pill ${priorityClass(x.priority)}">${esc(x.priority)}</span><span>${esc(x.status)}</span></div><button class="link-btn" data-edit-row="${x.row}">Edit</button></div>`).join('')}`:''}${r.length?`<h3>Routines</h3>${routineRows(r)}`:''}${!a.length&&!r.length?empty('Clear day.') :''}</div>`;}

function renderRoutines(){const d=new Date();const groups={Daily:[],Monthly:[],Quarterly:[],Annually:[]};(state.data.routines||[]).forEach(r=>(groups[r.frequency]||groups.Daily).push(r));return Object.entries(groups).map(([g,items])=>section(g, state.data.app.scheduleRules[g]||'', items.length?items.map(r=>`<div class="log-row"><strong>${esc(r.task)}</strong><div class="meta"><span>${esc(r.document||'')}</span></div></div>`).join(''):empty('None'))).join('');}
function renderDaily(){const rows=(state.data.dailyLog||[]).slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));return `<div class="card"><div class="card-head"><div><h3>Daily Log</h3><p>What happened that may matter later.</p></div><button class="btn primary" data-new-daily>+ Log Entry</button></div><div class="card-body">${rows.length?rows.map(x=>`<div class="log-row"><strong>${esc(x.summary)}</strong><div class="meta"><span>${esc(fmtDate(x.date))}</span><span>${esc(x.type)}</span><span>${esc(x.significance)}</span>${x.projectId?`<span>${esc(x.projectId)}</span>`:''}</div>${x.details?`<div class="muted" style="margin-top:6px">${esc(x.details)}</div>`:''}</div>`).join(''):empty('No entries yet.')}</div></div>`;}
function renderBrag(){const rows=(state.data.brag||[]).slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));return `<div class="card"><div class="card-head"><div><h3>Brag Sheet</h3><p>Wins worth remembering.</p></div><button class="btn primary" data-new-brag>+ Add Win</button></div><div class="card-body">${rows.length?rows.map(x=>`<div class="brag-row"><strong>${esc(x.accomplishment)}</strong><div class="meta"><span>${esc(fmtDate(x.date))}</span><span>${esc(x.category)}</span>${x.metric?`<span>${esc(x.metric)}</span>`:''}</div>${x.impact?`<div class="muted" style="margin-top:6px">${esc(x.impact)}</div>`:''}</div>`).join(''):empty('No wins yet.')}</div></div>`;}
function renderProjects(){const p=state.data.projects||[];return `<div class="project-grid">${p.map(x=>`<button class="project-tile" data-project="${esc(x.projectId)}"><h3>${esc(x.projectName)}</h3><div class="meta"><span class="status-dot ${String(x.health).toLowerCase()}"></i>${esc(x.health)}</span><span>${esc(x.status)}</span></div><div class="meta"><span>${esc(x.projectId)}</span>${x.targetDate?`<span>Target ${esc(fmtDate(x.targetDate))}</span>`:''}</div></button>`).join('')}${!p.length?empty('No projects yet.'):''}</div><button class="btn primary" data-new-project>+ New Project</button>`;}
function renderMoreSheet(){openSheet('More',`<div class="more-grid">${nav.slice(3).map(([r,i,l])=>`<button class="more-card" data-more-route="${r}"><strong>${i} ${l}</strong><span>Open ${l}</span></button>`).join('')}</div>`);}
